``` r
library(MASS)
summary(Boston)
```

    ##       crim                zn             indus            chas        
    ##  Min.   : 0.00632   Min.   :  0.00   Min.   : 0.46   Min.   :0.00000  
    ##  1st Qu.: 0.08204   1st Qu.:  0.00   1st Qu.: 5.19   1st Qu.:0.00000  
    ##  Median : 0.25651   Median :  0.00   Median : 9.69   Median :0.00000  
    ##  Mean   : 3.61352   Mean   : 11.36   Mean   :11.14   Mean   :0.06917  
    ##  3rd Qu.: 3.67708   3rd Qu.: 12.50   3rd Qu.:18.10   3rd Qu.:0.00000  
    ##  Max.   :88.97620   Max.   :100.00   Max.   :27.74   Max.   :1.00000  
    ##       nox               rm             age              dis        
    ##  Min.   :0.3850   Min.   :3.561   Min.   :  2.90   Min.   : 1.130  
    ##  1st Qu.:0.4490   1st Qu.:5.886   1st Qu.: 45.02   1st Qu.: 2.100  
    ##  Median :0.5380   Median :6.208   Median : 77.50   Median : 3.207  
    ##  Mean   :0.5547   Mean   :6.285   Mean   : 68.57   Mean   : 3.795  
    ##  3rd Qu.:0.6240   3rd Qu.:6.623   3rd Qu.: 94.08   3rd Qu.: 5.188  
    ##  Max.   :0.8710   Max.   :8.780   Max.   :100.00   Max.   :12.127  
    ##       rad              tax           ptratio          black       
    ##  Min.   : 1.000   Min.   :187.0   Min.   :12.60   Min.   :  0.32  
    ##  1st Qu.: 4.000   1st Qu.:279.0   1st Qu.:17.40   1st Qu.:375.38  
    ##  Median : 5.000   Median :330.0   Median :19.05   Median :391.44  
    ##  Mean   : 9.549   Mean   :408.2   Mean   :18.46   Mean   :356.67  
    ##  3rd Qu.:24.000   3rd Qu.:666.0   3rd Qu.:20.20   3rd Qu.:396.23  
    ##  Max.   :24.000   Max.   :711.0   Max.   :22.00   Max.   :396.90  
    ##      lstat            medv      
    ##  Min.   : 1.73   Min.   : 5.00  
    ##  1st Qu.: 6.95   1st Qu.:17.02  
    ##  Median :11.36   Median :21.20  
    ##  Mean   :12.65   Mean   :22.53  
    ##  3rd Qu.:16.95   3rd Qu.:25.00  
    ##  Max.   :37.97   Max.   :50.00

1.  an estimate for the population mean of `medv`

``` r
mu_hat = mean(Boston$medv)
mu_hat
```

    ## [1] 22.53281

1.  estimate of the standard error of `mu_hat`

``` r
mu_err = sd(Boston$medv)/ sqrt(length(Boston$medv))
mu_err
```

    ## [1] 0.4088611

1.  Now estimate the standard error of `mu_hat` using the bootstrap.

``` r
library(boot)
boot.fn = function(data, index) {
  return(mean(data[index]))
}
btstrap = boot(Boston$medv, boot.fn, 1000)
btstrap
```

    ## 
    ## ORDINARY NONPARAMETRIC BOOTSTRAP
    ## 
    ## 
    ## Call:
    ## boot(data = Boston$medv, statistic = boot.fn, R = 1000)
    ## 
    ## 
    ## Bootstrap Statistics :
    ##     original      bias    std. error
    ## t1* 22.53281 0.001548814   0.4236055

Similar to answer from (b) up to two significant digits. (0.4020 vs 0.4089)

95 % confidence interval for the mean of `medv`

`[ˆμ − 2SE(ˆμ), μˆ + 2SE(ˆμ)]`

``` r
conf_int = c(mu_hat - 2*0.4020, mu_hat + 2*0.4020)
conf_int
```

    ## [1] 21.72881 23.33681

Compare it to the results obtained using `t.test(Boston$medv)`

``` r
t.test(Boston$medv)
```

    ## 
    ##  One Sample t-test
    ## 
    ## data:  Boston$medv
    ## t = 55.111, df = 505, p-value < 2.2e-16
    ## alternative hypothesis: true mean is not equal to 0
    ## 95 percent confidence interval:
    ##  21.72953 23.33608
    ## sample estimates:
    ## mean of x 
    ##  22.53281

Boostrap estimate equal to t-test upto two decimal places.

``` r
medv.med = median(Boston$medv)
medv.med
```

    ## [1] 21.2

We now would like to estimate the standard error of `ˆμmed`. Unfortunately, there is no simple formula for computing the standard error of the median. Instead, estimate the standard error of the median using the bootstrap.

``` r
boot.fn = function(data, index) return(median(data[index]))
boot(Boston$medv, boot.fn, 1000)
```

    ## 
    ## ORDINARY NONPARAMETRIC BOOTSTRAP
    ## 
    ## 
    ## Call:
    ## boot(data = Boston$medv, statistic = boot.fn, R = 1000)
    ## 
    ## 
    ## Bootstrap Statistics :
    ##     original  bias    std. error
    ## t1*     21.2 -0.0263   0.3831646

Median of 21.2 with SE of 0.380. Small standard error relative to median value.

an estimate for the tenth percentile of `medv` in Boston suburbs

``` r
medv_tenth = quantile(Boston$medv, c(0.1))
medv_tenth
```

    ##   10% 
    ## 12.75

Use the bootstrap to estimate the standard error for above.

``` r
boot.fn = function(data, index) return(quantile(data[index], c(0.1)))
boot(Boston$medv, boot.fn, 1000)
```

    ## 
    ## ORDINARY NONPARAMETRIC BOOTSTRAP
    ## 
    ## 
    ## Call:
    ## boot(data = Boston$medv, statistic = boot.fn, R = 1000)
    ## 
    ## 
    ## Bootstrap Statistics :
    ##     original  bias    std. error
    ## t1*    12.75 -0.0217   0.5032966

Tenth-percentile of 12.75 with SE of 0.511. Small standard error relative to tenth-percentile value.
